### ISSUE TITLE
can not search

### ISSUE THREAD

**Issue by samandarkuchkarov** [Nathan-Feng/Android-TV-Recommend-Demo#1]
i cloned app and successfully run, but in android tv searched aaa can not find anything from this app after i tried name from suggested text in database and also dont find anything but if i search other videos from other apps it gives result, i checked setting and global search was turn on in app

**Comment by Nathan-Feng** [comment]
Hi samandarkuchkarov,
Sorry for my reply late,
this demo only work on Android 10.0 ,but maybe different for some chipset (such as qcom or MTK) 
if not working ,please check google TAM for help 

Sorry for not being able to help you

**Comment by samandarkuchkarov** [comment]
i see, thank you for your reply
